[package]
name = "koharu"
default-run = "koharu"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
publish.workspace = true
license.workspace = true

[features]
default = ["tauri/cef"]

[dependencies]
clap = { workspace = true }
console = { workspace = true }
koharu-app = { workspace = true }
koharu-desktop = { workspace = true }
koharu-torch-sys = { workspace = true }
rfd = { workspace = true }
sentry = { workspace = true }
serde_json = { workspace = true }
tauri = { workspace = true }
tauri-plugin-opener = { workspace = true }
tauri-plugin-process = { workspace = true }
tauri-plugin-updater = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = ["Win32_System_Console"] }

[build-dependencies]
tauri-build = { workspace = true }
